### ISSUE TITLE
Searching for matching objects within an array?

### ISSUE THREAD

**Issue by cpick** [gmmorris/jg#2]
Thanks for releasing this tool!
I've just started kicking the tires and was wondering if it was possible to search within an array of objects for elements that match certain properties?

Eg something like the following:
```sh
$ jg '[={"id":"foo"}]' << EOF
> [
>   {
>     "id": "foo",
>     "value": "bar"
>   },
>   {
>     "id": "baz",
>     "value": "qux"
>   }
> ]
> EOF
{
  "id": "foo",
  "value": "bar"
}
```

**Comment by gmmorris** [comment]
Hi Chris,
My pleasure, thanks for your kind words.

Yes, absolutely, it's possible to match against an object in an array but a couple of things to keep in mind:

1. The selector you want is: _'[{"id":"foo"}]'_, drop the _=_
1. The result is going to be *the whole line* that matches, not just the matched object.
1. The input needs to be a single line, so your file can't have a pretty printed JSON, but rather a valid JSON on every single line (as you'd expect to find in a JSON structured log).

This is because **jg** is meant to work as an equivalent to **grep**.

It sound like what you're looking for might be an equivalent to **sed** or **awk** (rather than **grep**), so you might want to check out [jq](https://stedolan.github.io/jq/) which fills that space nicely.

**Comment by cpick** [comment]
Ah, the line-by-line matching was not obvious to me.  I knew that `jg` was attempting to be `grep`-like but I thought that was in a more high-level manner.  My mental model was that much like `grep` would help you search within a file for a relevant line, I thought `jg` it would help you semantically search within an (arbitrarily deep) JSON object for a relevant sub-object/field (irrespective of whitespace).

Most of my use-cases are actually JSON structured logs so I think `jg` will work great, but sometimes I end up with something like a JSON array of objects and I'm looking for a particular subset of them.  I do currently use `jq` for this task, but it's query language is pretty cumbersome/unintuitive.  I'll probably whip up some script to reformat these arrays of objects into one object per line and see if `jg` ends up feeling more natural.

**Comment by gmmorris** [comment]
Thanks for the feedback, I'll try and improve the docs to make that clearer.
You might not need to reformat it, as jg can be used as a pipe, so perhaps you can use jq to pluck out all the json objects, output them as line by line and pipe that into jg? 

I haven't tried it yet (am afk at the moment) but I think that should work.

**Comment by cpick** [comment]
That's exactly what I just tested.  It's a little cumbersome, but I think it'll work for my use case:

```sh
$ jq -c '.[]' << EOF | jg '{"id":"foo"}' | jq .
> [
>   {
>     "id": "foo",
>     "value": "bar"
>   },
>   {
>     "id": "baz",
>     "value": "qux"
>   }
> ]
> EOF
{
  "id": "foo",
  "value": "bar"
}
```

**Comment by gmmorris** [comment]
Awesome so glad jg is coming in handy 👍

If you have any more feedback or issues please do let me know. 
Keeping this open for now as a reminder to make the docs clearer about the input format.

**Comment by gmmorris** [comment]
Updated the docs.
Thanks for your time Chris, please do let me know if you have any other feedback.

Cheers
